//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DatabaseLevel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBEntities object using the connection string found in the 'DBEntities' section of the application configuration file.
        /// </summary>
        public DBEntities() : base("name=DBEntities", "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntities object.
        /// </summary>
        public DBEntities(string connectionString) : base(connectionString, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntities object.
        /// </summary>
        public DBEntities(EntityConnection connection) : base(connection, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DB> DB
        {
            get
            {
                if ((_DB == null))
                {
                    _DB = base.CreateObjectSet<DB>("DB");
                }
                return _DB;
            }
        }
        private ObjectSet<DB> _DB;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DB_Version> DB_Version
        {
            get
            {
                if ((_DB_Version == null))
                {
                    _DB_Version = base.CreateObjectSet<DB_Version>("DB_Version");
                }
                return _DB_Version;
            }
        }
        private ObjectSet<DB_Version> _DB_Version;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Field> Field
        {
            get
            {
                if ((_Field == null))
                {
                    _Field = base.CreateObjectSet<Field>("Field");
                }
                return _Field;
            }
        }
        private ObjectSet<Field> _Field;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Field_Type> Field_Type
        {
            get
            {
                if ((_Field_Type == null))
                {
                    _Field_Type = base.CreateObjectSet<Field_Type>("Field_Type");
                }
                return _Field_Type;
            }
        }
        private ObjectSet<Field_Type> _Field_Type;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sample_Data> Sample_Data
        {
            get
            {
                if ((_Sample_Data == null))
                {
                    _Sample_Data = base.CreateObjectSet<Sample_Data>("Sample_Data");
                }
                return _Sample_Data;
            }
        }
        private ObjectSet<Sample_Data> _Sample_Data;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Table> Table
        {
            get
            {
                if ((_Table == null))
                {
                    _Table = base.CreateObjectSet<Table>("Table");
                }
                return _Table;
            }
        }
        private ObjectSet<Table> _Table;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkPlace> WorkPlace
        {
            get
            {
                if ((_WorkPlace == null))
                {
                    _WorkPlace = base.CreateObjectSet<WorkPlace>("WorkPlace");
                }
                return _WorkPlace;
            }
        }
        private ObjectSet<WorkPlace> _WorkPlace;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DB EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDB(DB dB)
        {
            base.AddObject("DB", dB);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DB_Version EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDB_Version(DB_Version dB_Version)
        {
            base.AddObject("DB_Version", dB_Version);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Field EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToField(Field field)
        {
            base.AddObject("Field", field);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Field_Type EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToField_Type(Field_Type field_Type)
        {
            base.AddObject("Field_Type", field_Type);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sample_Data EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSample_Data(Sample_Data sample_Data)
        {
            base.AddObject("Sample_Data", sample_Data);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Table EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTable(Table table)
        {
            base.AddObject("Table", table);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkPlace EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkPlace(WorkPlace workPlace)
        {
            base.AddObject("WorkPlace", workPlace);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="DB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DB : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DB object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static DB CreateDB(global::System.Int32 id)
        {
            DB dB = new DB();
            dB.id = id;
            return dB;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_workplace
        {
            get
            {
                return _id_workplace;
            }
            set
            {
                Onid_workplaceChanging(value);
                ReportPropertyChanging("id_workplace");
                _id_workplace = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_workplace");
                Onid_workplaceChanged();
            }
        }
        private Nullable<global::System.Int32> _id_workplace;
        partial void Onid_workplaceChanging(Nullable<global::System.Int32> value);
        partial void Onid_workplaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_version
        {
            get
            {
                return _id_version;
            }
            set
            {
                Onid_versionChanging(value);
                ReportPropertyChanging("id_version");
                _id_version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_version");
                Onid_versionChanged();
            }
        }
        private Nullable<global::System.Int32> _id_version;
        partial void Onid_versionChanging(Nullable<global::System.Int32> value);
        partial void Onid_versionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="DB_Version")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DB_Version : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DB_Version object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static DB_Version CreateDB_Version(global::System.Int32 id)
        {
            DB_Version dB_Version = new DB_Version();
            dB_Version.id = id;
            return dB_Version;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    //ПРИШЛОСЬ ЗАКОМЕНТИРОВАТЬ. ОШИБКИ

    [EdmEntityTypeAttribute(NamespaceName = "DBModel", Name = "Field")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class FieldDb : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Field object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static FieldDb CreateField(global::System.Int32 id)
        {
            FieldDb field = new FieldDb();
            field.id = id;
            return field;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_table
        {
            get
            {
                return _id_table;
            }
            set
            {
                Onid_tableChanging(value);
                ReportPropertyChanging("id_table");
                _id_table = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_table");
                Onid_tableChanged();
            }
        }
        private Nullable<global::System.Int32> _id_table;
        partial void Onid_tableChanging(Nullable<global::System.Int32> value);
        partial void Onid_tableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_type
        {
            get
            {
                return _id_type;
            }
            set
            {
                Onid_typeChanging(value);
                ReportPropertyChanging("id_type");
                _id_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_type");
                Onid_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _id_type;
        partial void Onid_typeChanging(Nullable<global::System.Int32> value);
        partial void Onid_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_null
        {
            get
            {
                return _is_null;
            }
            set
            {
                Onis_nullChanging(value);
                ReportPropertyChanging("is_null");
                _is_null = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_null");
                Onis_nullChanged();
            }
        }
        private Nullable<global::System.Int32> _is_null;
        partial void Onis_nullChanging(Nullable<global::System.Int32> value);
        partial void Onis_nullChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_index
        {
            get
            {
                return _is_index;
            }
            set
            {
                Onis_indexChanging(value);
                ReportPropertyChanging("is_index");
                _is_index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_index");
                Onis_indexChanged();
            }
        }
        private Nullable<global::System.Int32> _is_index;
        partial void Onis_indexChanging(Nullable<global::System.Int32> value);
        partial void Onis_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Field_Type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Field_Type : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Field_Type object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Field_Type CreateField_Type(global::System.Int32 id)
        {
            Field_Type field_Type = new Field_Type();
            field_Type.id = id;
            return field_Type;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Sample_Data")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sample_Data : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sample_Data object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Sample_Data CreateSample_Data(global::System.Int32 id)
        {
            Sample_Data sample_Data = new Sample_Data();
            sample_Data.id = id;
            return sample_Data;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_field
        {
            get
            {
                return _id_field;
            }
            set
            {
                Onid_fieldChanging(value);
                ReportPropertyChanging("id_field");
                _id_field = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_field");
                Onid_fieldChanged();
            }
        }
        private Nullable<global::System.Int32> _id_field;
        partial void Onid_fieldChanging(Nullable<global::System.Int32> value);
        partial void Onid_fieldChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Table object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Table CreateTable(global::System.Int32 id)
        {
            Table table = new Table();
            table.id = id;
            return table;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_db
        {
            get
            {
                return _id_db;
            }
            set
            {
                Onid_dbChanging(value);
                ReportPropertyChanging("id_db");
                _id_db = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_db");
                Onid_dbChanged();
            }
        }
        private Nullable<global::System.Int32> _id_db;
        partial void Onid_dbChanging(Nullable<global::System.Int32> value);
        partial void Onid_dbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> count_record
        {
            get
            {
                return _count_record;
            }
            set
            {
                Oncount_recordChanging(value);
                ReportPropertyChanging("count_record");
                _count_record = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("count_record");
                Oncount_recordChanged();
            }
        }
        private Nullable<global::System.Int32> _count_record;
        partial void Oncount_recordChanging(Nullable<global::System.Int32> value);
        partial void Oncount_recordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="WorkPlace")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkPlace : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkPlace object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static WorkPlace CreateWorkPlace(global::System.Int32 id)
        {
            WorkPlace workPlace = new WorkPlace();
            workPlace.id = id;
            return workPlace;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
    }

    #endregion

    
}
